modalDevs
sepaev/filmoteka pull request #3
Opened 2021-08-07 19:01 UTC by Dmytro78

start1

2021-08-07 19:33 UTC, sepaev requested changes

2021-08-07 19:33 UTC, sepaev commented on src/partials/modalDevs.html
> +<modal-devs class="modal-devs is-hidden" data-modal>
Вернуть тег <section> вместо тега <modal-devs> думаю это по ошибке сделано.

2021-08-07 19:33 UTC, sepaev commented on src/partials/modalDevs.html
> +      <div class="team-Lead">
Поменять класс на "team-list__lead". С маленькой буквы. И в sass внести его в группу "team-list" вот так "&__lead{...}"

2021-08-07 19:33 UTC, sepaev commented on src/partials/modalDevs.html
> +              <svg class="networks__img" width="32" height="32">
Не вижу родителя у класса networks. Это разрешено, но в крайних мерах. В данном же случае нет такой необходимости лучше использовать team-list__networks-item и team-list__networks-img с последующим добавлением в sass к родителю ".team-list" с селектором "&__networks-item" и "&__networks-img" и везде так поменять

2021-08-08 10:21 UTC, Dmytro78 commented on src/partials/modalDevs.html
> +              <svg class="networks__img" width="32" height="32">
добавил <ul class="networks">

2021-08-08 10:22 UTC, Dmytro78 commented on src/partials/modalDevs.html
> +              <svg class="networks__img" width="32" height="32">
добавил ul class=networks

2021-08-08 10:22 UTC, Dmytro78 commented on src/partials/modalDevs.html
> +<modal-devs class="modal-devs is-hidden" data-modal>
вернул

2021-08-08 10:55 UTC, Dmytro78 commented on src/partials/modalDevs.html
> +      <div class="team-Lead">
+

2021-08-08 11:25 UTC, merged